apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end-hpa
  namespace: tech-challenge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-front-end
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50