{{ if .Values.Deployment.FrontEndDp.create }}
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dp-front-end
  namespace: tech-challenge
spec:
  selector:
    matchLabels:
      deployment: dp-front-end
  replicas: {{ .Values.Deployment.FrontEndDp.spec.replica }}
  template:
    metadata:
      labels:
        deployment: dp-front-end
    spec:
      containers:
        - name: dp-front-end
          image: servian/techchallengeapp:latest
          # args: ["serve"]
          # args: ["updatedb", "-s"]
          command: ["/bin/sh"]
          args: ["-c", "sh ./deployment.sh"]

          ports:
          - containerPort: 3000
            # name: http
          volumeMounts:
          - name: config-volume
            mountPath: /TechChallengeApp/conf.toml
            subPath: conf.toml
          - name: deployment-script-volume
            mountPath: /TechChallengeApp/deployment.sh
            subPath: deployment.sh
      volumes:
        - name: config-volume
          configMap:
            name: front-end-config
        - name: deployment-script-volume
          configMap:
            name: frontend-deployment-script
            defaultMode: 0777
{{ end }}